export const free = {
    id: 5555,
    chargifyId: 7777,
    apiHandle: 'free-2021',
    name: 'Free',
    subtitle: null,
    features: [
        '50GB Free Monthly Bandwidth',
        'Storage for 3 Videos',
        'Video Customization \u0026 Smart Autoplay Features',
        'No Credit Card Required',
    ],
    price: '0.00',
    trialPrice: '0.00',
    creditCardRequired: false,
    setupFeeInCents: null,
    hasTrial: false,
    isFree: true,
    isPublished: true,
    billingMode: 'bandwidth',
    billingPeriod: '1 month',
    trialPeriod: null,
    bandwidth: 50,
    videoSpace: 3,
    encoding: 'standard',
    extraBandwidthPrice: 0,
    extraBandwidthUnit: 'GB',
    extraVideoSpacePrice: 1,
    tier: 'free',
    upsellPage: null,
    upsellMainProducts: null,
}

export const pro = {
    id: 555,
    chargifyId: 777,
    apiHandle: 'pro-nc',
    name: 'Pro',
    subtitle: null,
    features: [
        '200 GB Bandwidth per Month ',
        'Unbranded Video Player ',
        'Video Analytics, Tags, Play Gates \u0026 Integrations',
        'Chat \u0026 Email Support',
    ],
    price: '79.00',
    trialPrice: '0.00',
    creditCardRequired: false,
    setupFeeInCents: null,
    hasTrial: true,
    isFree: false,
    isPublished: false,
    billingMode: 'bandwidth',
    billingPeriod: '1 month',
    trialPeriod: '14 day',
    bandwidth: 200,
    videoSpace: 20,
    encoding: 'premium',
    extraBandwidthPrice: 0.33,
    extraBandwidthUnit: 'GB',
    extraVideoSpacePrice: 0.25,
    tier: 'pro',
    upsellPage: null,
    upsellMainProducts: null,
}

export const enterprise = {
    id: 118,
    chargifyId: 5985267,
    apiHandle: 'premium',
    name: 'Premium',
    subtitle: null,
    features: [
        '400 GB Bandwidth per Month ',
        '25\u00a2 per Extra GB',
        'Email \u0026 Chat Support',
        'Unbranded Video Player ',
        'Store Extra Videos for 25\u00a2 Each',
    ],
    price: '149.00',
    trialPrice: '0.00',
    creditCardRequired: false,
    setupFeeInCents: null,
    hasTrial: false,
    isFree: false,
    isPublished: true,
    billingMode: 'bandwidth',
    billingPeriod: '1 month',
    trialPeriod: '14 day',
    bandwidth: 400,
    videoSpace: 100,
    encoding: 'premium',
    extraBandwidthPrice: 0,
    extraBandwidthUnit: 'GB',
    extraVideoSpacePrice: 0.25,
    tier: 'enterprise',
    upsellPage: null,
    upsellMainProducts: null,
    skipBillingPageAtSignup: false,
}

export const customerSubscriptionMock = {
    id: 999,
    chargifyId: 777,
    creditCard: null,
    dateNextBilling: '2022-11-29',
    daysTillPeriodEnds: 13,
    lastPaymentAmount: '0.00',
    lastPaymentDate: '2022-11-15',
    bandwidthLimit: '200.00',
    bandwidthLimitInMB: 204800,
    bandwidthOverage: '0.00',
    bandwidthOverageInMB: 0,
    bandwidthUsed: '0.00',
    bandwidthUsedInMB: 0,
    billingMode: 'bandwidth',
    plan: pro,
    planNext: free,
    referredFriends: 0,
    totalCost: '0.00',
    videoSpaceLimit: 20,
    videoSpaceOverage: 0,
    videoSpaceUsed: 0,
    status: 'trial',
    isActive: true,
}

export const plansMock = [
    free,
    pro,
    {
        id: 99999,
        chargifyId: 8888,
        apiHandle: 'premium',
        name: 'Premium',
        subtitle: null,
        features: [
            '500 GB Bandwidth per Month ',
            'Unbranded Video Player ',
            'Priority Support',
            'Early access to premium features',
        ],
        price: '149.00',
        trialPrice: '0.00',
        creditCardRequired: true,
        setupFeeInCents: null,
        hasTrial: true,
        isFree: false,
        isPublished: true,
        billingPeriod: '1 month',
        trialPeriod: '14 day',
        bandwidth: 500,
        videoSpace: 50,
        encoding: 'premium',
        extraBandwidthPrice: 0,
        extraBandwidthUnit: 'GB',
        extraVideoSpacePrice: 0.25,
        tier: 'enterprise',
        upsellPage: null,
        upsellMainProducts: null,
    },
]

export const CUSTOMER_MOCK = {
    firstname: 'Test',
    lastname: 'Test4',
    email: 'TestTest4@vidalytics.com',
    guid: 'gggg4444',
    dateCreated: '2022-11-15T13:35:00+00:00',
    status: 'trial',
    hasUploadedVideo: false,
    featureFlags: {},
}
